apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    # Event-Source can listen to multiple HTTP servers. Define a unique port for each
    argo-ci-event:
      # Port to rin the http server on
      port: "12000"
      endpoint: argo-ci-event
      method: POST
